import { Listing } from '../types/listing';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    host_id: 'host1',
    category_id: 'cat_retreat',
    category_name: 'Retreat',
    title: 'Silent Forest Retreat',
    description: 'A 3-day silent retreat in the heart of the forest.',
    location_address: 'Blackwood Forest, OR',
    location_latitude: 45.523062,
    location_longitude: -122.676482,
    price: 450,
    currency: 'USD',
    duration_minutes: null,
    start_date: '2026-07-15',
    end_date: '2026-07-18',
    capacity: 10,
    status: 'published',
    average_rating: 4.8,
  },
  {
    id: '2',
    host_id: 'host2',
    category_id: 'cat_meditation',
    category_name: 'Meditation',
    title: 'Morning Zen Session',
    description: 'Start your day with a peaceful silent meditation.',
    location_address: 'Downtown Zen Center, Portland',
    location_latitude: 45.523062,
    location_longitude: -122.676482,
    price: 25,
    currency: 'USD',
    duration_minutes: 60,
    start_date: null,
    end_date: null,
    capacity: 20,
    status: 'published',
    average_rating: 4.9,
  },
  {
    id: '3',
    host_id: 'host3',
    category_id: 'cat_walk',
    category_name: 'Silent Walk',
    title: 'Coastal Mindfulness Walk',
    description: 'Walk in silence along the beautiful coastline.',
    location_address: 'Cannon Beach, OR',
    location_latitude: 45.8917,
    location_longitude: -123.9615,
    price: 35,
    currency: 'USD',
    duration_minutes: 120,
    start_date: null,
    end_date: null,
    capacity: 15,
    status: 'published',
    average_rating: 4.7,
  },
  {
    id: '4',
    host_id: 'host4',
    category_id: 'cat_biking',
    category_name: 'Silent Biking',
    title: 'Mountain Path Silent Ride',
    description: 'Experience the rhythm of your breath while biking.',
    location_address: 'Mount Hood, OR',
    location_latitude: 45.3736,
    location_longitude: -121.6960,
    price: 50,
    currency: 'USD',
    duration_minutes: 180,
    start_date: null,
    end_date: null,
    capacity: 8,
    status: 'published',
    average_rating: 4.5,
  },
  {
    id: '5',
    host_id: 'host1',
    category_id: 'cat_workshop',
    category_name: 'Workshop',
    title: 'Art of Silence Workshop',
    description: 'Learn how to integrate silence into your daily life.',
    location_address: 'Creative Hub, Portland',
    location_latitude: 45.5230,
    location_longitude: -122.6765,
    price: 80,
    currency: 'USD',
    duration_minutes: 240,
    start_date: null,
    end_date: null,
    capacity: 12,
    status: 'published',
    average_rating: 4.6,
  },
];
